import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { GetStaticProps, GetServerSideProps } from "next";
import { scanArticleDir } from "@/utils";
import { BLOG_ARTICLE_DIR } from "@/configs/index";
import { IDirRecord } from "@/interfaces/article";
import MiniArticle from "@/components/MiniArticle";

const Home: NextPage = ({ dirInfo }: { dirInfo: IDirRecord }) => {
  console.log("dirInfo:", dirInfo);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex px-4">
        <section className="flex-grow ">
          <ul>
            {dirInfo.articleList.map((i, idx) => (
              <li key={idx} className=" my-8 rounded-md ">
                <MiniArticle {...i} />
              </li>
            ))}
          </ul>
        </section>
        <aside className="w-36 bg-purple-50 p-4">
          <ul>
            {dirInfo.children.map((i, idx) => (
              <li key={idx}>{i.dirName}</li>
            ))}
          </ul>
        </aside>
      </div>
    </>
  );
};

export default Home;

// return props to current page component as props
export const getStaticProps: GetStaticProps = async (context) => {
  const dirInfo = await scanArticleDir(BLOG_ARTICLE_DIR);

  return {
    props: {
      dirInfo,
    },
  };
};
