name: Deploy on Master Push or Issue Change

on:
  push:
    branches:
      - master
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Deploy Hook
        run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/16710477-1a3d-4b98-9a4e-173df1f073f5
      - name: Create notification
        run: curl -d "Hi" ntfy.sh/aaron-conlon-blog-rebuild